=== imila254/IT/XML-JSON-XSD/IT-1lab_namespace.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.imuzika.lt"
xmlns:mano ="https://www.imuzika.lt"
xmlns ="https://www.imuzika.lt"
elementFormDefault="qualified" 
>
<xs:element name="MuzikiniųAlbumųParduotuvė" type="TipasMuzikiniųAlbumųParduotuvė">
    <xs:key name="AtlikėjoIdRaktas">
        <xs:selector xpath="mano:Atlikėjai/mano:Atlikėjas|mano:Grupės/mano:Grupė"/>
        <xs:field xpath="@id"/>
    </xs:key>
    <xs:keyref name="NuorodaĮAtlikėjoID" refer="AtlikėjoIdRaktas">
        <xs:selector xpath="mano:Albumai/mano:AlbumoTipas/mano:Albumas/mano:Autorius"/>
        <xs:field xpath="@idref"/>
    </xs:keyref>
</xs:element>
<xs:complexType name="TipasMuzikiniųAlbumųParduotuvė">
    <xs:sequence>
        <xs:element name="Atlikėjai" type="TipasAtlikėjai" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Grupės" type="TipasGrupės" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Albumai" type="TipasAlbumai" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="TipasAtlikėjai">
    <xs:sequence>
        <xs:element name="Atlikėjas" type="TipasAtlikėjasSuAtributu" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="TipasAtlikėjas">
    <xs:choice>
        <xs:sequence>
            <xs:element name="Vardas" type="xs:string"/>
            <xs:element name="Pavardė" type="xs:string"/>
        </xs:sequence>
        <xs:element name="Pseudonimas" type="xs:string"/>
    </xs:choice>

</xs:complexType>

<xs:complexType name="TipasAtlikėjasSuAtributu">
    <xs:complexContent>
        <xs:extension base="TipasAtlikėjas">
            <xs:attribute name="id" type="TipasId" use="required"/>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<xs:simpleType name="TipasId">
    <xs:restriction base="xs:string">
        <xs:pattern value="[a-z][0-9]"/>
    </xs:restriction>
</xs:simpleType>


<xs:complexType name="TipasGrupės">
    <xs:sequence>
        <xs:element name="Grupė" type="TipasGrupė" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="TipasGrupė" mixed="true">
    <xs:sequence>
        <xs:element name="Pavadinimas" type="xs:string" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="id" type="TipasId" use="required"/>
</xs:complexType>


<xs:complexType name="TipasAlbumai">
    <xs:sequence>
        <xs:element name="AlbumoTipas" type="TipasAlbumoTipas" minOccurs="3" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>


<xs:complexType name="TipasAlbumoTipas">
    <xs:sequence>
        <xs:element name="Albumas" type="TipasAlbumasSuApribojimu" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="tipas" type="Tipas" use="required"/>
</xs:complexType>

<xs:simpleType name="Tipas">
    <xs:restriction base="xs:string">
        <xs:enumeration value="CD" />
        <xs:enumeration value="Vinilas"/>
        <xs:enumeration value="Kasetė"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="TipasAlbumas">
    <xs:sequence>
        <xs:element name="Pavadinimas" type="xs:string" maxOccurs="unbounded"/>
        <xs:element name="Stilius" type="xs:string"/>
        <xs:element name="Autorius" type="TipasAutorius"/>
        <xs:element name="IšleidimoData" type="TipasData"/>
        <xs:element name="Kaina"  type="ApribotaKainaSuAtributu"/>
    </xs:sequence>
    <xs:attribute name="UPS" type="TipasUPS" use="required"/>
</xs:complexType>

<xs:complexType name="TipasAlbumasSuApribojimu">
    <xs:complexContent>
        <xs:restriction base="TipasAlbumas">
            <xs:sequence>
                <xs:element name="Pavadinimas" type="xs:string" maxOccurs="1"/>
                <xs:element name="Stilius" type="xs:string"/>
                <xs:element name="Autorius" type="TipasAutorius"/>
                <xs:element name="IšleidimoData" type="TipasData"/>
                <xs:element name="Kaina"  type="ApribotaKainaSuAtributu"/>
            </xs:sequence>
        </xs:restriction>
    </xs:complexContent>
</xs:complexType>

<xs:simpleType name="DatosListas">
    <xs:list itemType="xs:integer"/>
</xs:simpleType>

<xs:simpleType name='TipasData'>
    <xs:restriction base='DatosListas'>
        <xs:pattern value="([12]\d{3} (0[1-9]|1[0-2]) (0[1-9]|[12]\d|3[01]))"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="TipasUPS">
    <xs:restriction base="xs:string">
        <xs:pattern value="[0-9]{13}"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="TipasAutorius">
    <xs:simpleContent>
        <xs:extension base="xs:string">
           <xs:attribute name="idref" type="TipasId" use="required"/> 
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:simpleType name="TipasKaina">
    <xs:restriction base="xs:decimal">
        <xs:minExclusive value="1.00"/>
    </xs:restriction>
</xs:simpleType>

<!--
<xs:simpleType name="TipasKainaSuApribojimu">
    <xs:restriction base="TipasKaina">
        <xs:minExclusive value="0.00"/>
    </xs:restriction>
</xs:simpleType>
-->

<xs:complexType name="TipasKainaSuAtributu">
    <xs:simpleContent>
        <xs:extension base="TipasKaina">
            <xs:attribute name="valiuta" type="TipasValiuta" use="required"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:complexType name="ApribotaKainaSuAtributu">
    <xs:simpleContent>
        <xs:restriction base="TipasKainaSuAtributu">
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleContent>
</xs:complexType>

<xs:simpleType name="TipasValiuta">
<xs:restriction base="xs:string">
    <xs:enumeration value="euras" />
    <xs:enumeration value="doleris"/>
    <xs:enumeration value="rublis"/>
</xs:restriction>
</xs:simpleType>

</xs:schema>

=== imila254/IT/XML-JSON-XSD/IT-1lab_namespace.xml
<?xml version="1.0" encoding="UTF-8"?>
<MuzikiniųAlbumųParduotuvė 
xmlns="https://www.imuzika.lt"
xsi:schemaLocation="https://www.imuzika.lt IT-1lab_namespace.xsd"
xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance">
    <Atlikėjai>
        <Atlikėjas id="a1">
            <Vardas>Taylor</Vardas>
            <Pavardė>Swift</Pavardė> 
        </Atlikėjas>
        <Atlikėjas id="a2">
            <Pseudonimas>Halsey</Pseudonimas>   
        </Atlikėjas>
        
    </Atlikėjai>
    <Grupės>
        <Grupė id="a3">
            <Pavadinimas>Onerepublic</Pavadinimas>
            Pastaba
        </Grupė>    
        <Grupė id="a4">
            <Pavadinimas>Imagine Dragons</Pavadinimas>
        </Grupė>  
    </Grupės>
    <Albumai>
        <AlbumoTipas tipas="CD">
            <Albumas UPS="4772222000001">
                <Pavadinimas>Evermore</Pavadinimas>
                <Stilius>Pop Rock</Stilius>
                <Autorius idref="a1"/>
                <IšleidimoData>2021 02 12</IšleidimoData>
                <Kaina valiuta="euras">17.00</Kaina>
            </Albumas>
            <Albumas UPS="4772222000003">
                <Pavadinimas>Manic</Pavadinimas>
                <Stilius>Pop</Stilius>
                <Autorius idref="a2"/>
                <IšleidimoData>2020 01 17</IšleidimoData>
                <Kaina valiuta="euras">17.00</Kaina>
            </Albumas>
            <Albumas UPS="4772222000005">
                <Pavadinimas>If I can't have love, I want power</Pavadinimas>
                <Stilius>Alternative rock</Stilius>
                <Autorius idref="a2"/>
                <IšleidimoData>2021 08 27</IšleidimoData>
                <Kaina valiuta="euras">17.00</Kaina>
            </Albumas>
            <Albumas UPS="4772222000006">
                <Pavadinimas>Human</Pavadinimas>
                <Stilius>Pop rock</Stilius>
                <Autorius idref="a3"/>
                <IšleidimoData>2021 08 27</IšleidimoData>
                <Kaina valiuta="euras">17.00</Kaina>
            </Albumas>
            <Albumas UPS="4772222000007">
                <Pavadinimas>Mercury-act</Pavadinimas>
                <Stilius>Pop rock</Stilius>
                <Autorius idref="a4"/>
                <IšleidimoData>2021 09 03</IšleidimoData>
                <Kaina valiuta="euras">17.00</Kaina>
            </Albumas>
        </AlbumoTipas>
        <AlbumoTipas tipas="Vinilas">
            <Albumas UPS="4772222000004">
                <Pavadinimas>If I can't have love, I want power</Pavadinimas>
                <Stilius>Alternative rock</Stilius>
                <Autorius idref="a2"/>
                <IšleidimoData>2021 08 27</IšleidimoData>
                <Kaina valiuta="euras">33.00</Kaina>
            </Albumas>
            <Albumas UPS="4772222000008">   
                <Pavadinimas>Mercury-act</Pavadinimas>
                <Stilius>Pop rock</Stilius>
                <Autorius idref="a4"/>
                <IšleidimoData>2021 09 03</IšleidimoData>
                <Kaina valiuta="euras">30.00</Kaina>
            </Albumas>
        </AlbumoTipas>
        <AlbumoTipas tipas="Kasetė">
            <Albumas UPS="4772222000002">
                <Pavadinimas>Evermore</Pavadinimas>
                <Stilius>Pop Rock</Stilius>
                <Autorius idref="a1"/>
                <IšleidimoData>2021 02 12</IšleidimoData>
                <Kaina valiuta="euras">17.00</Kaina>
            </Albumas>
        </AlbumoTipas>
    </Albumai>
</MuzikiniųAlbumųParduotuvė>
